name: 'Wait'
description: 'Wait a designated number of milliseconds'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()

inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache and restore'
    required: true
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  storage:
    description: 'Storage'
    required: true
outputs:
  result:
    description: "ss"