name: hello-world
on: push
jobs:
  my-job:
    if: ${{ github.event.act }}
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: |
          ls -lah
          apt update
          apt install zstd -y -qq
          npm install
      - name: Run
        uses: ./
        with:
          path: |
            node_modules
          key: npm-feature-${{ hashFiles('package-lock.json') }}
          storage: ./
      # - run: |
      #     ls -lah