name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Checkout the code
        uses: actions/checkout@v4
      - run: |
          apt update
          apt install zstd -y -qq
          npm install
      - name: Run
        uses: ./
        with:
          path: |
            node_modules
          key: "tst"
          storage: /tmp
      - run: |
          ls -lah